import FileUtil from "../../Util/FileUtil";
import dotenv from "dotenv";
dotenv.config();

export default class EmbeddedScriptBuilder
{
    async build(sourceDir?: string, targetDir?: string): Promise<void>
    {
        if (sourceDir == undefined)
            sourceDir = `${process.env.SRC_ROOT_DIR}/Shared`;
        if (targetDir == undefined)
            targetDir = `${process.env.VIEWS_ROOT_DIR}/embeddedScript`;

        let relativeFilePaths = await FileUtil.getAllRelativePathsInDirRecursively(sourceDir);
        relativeFilePaths = relativeFilePaths.filter(x => x.endsWith(".js"));

        for (const relativeFilePath of relativeFilePaths)
        {
            const sourceCode = (await FileUtil.read(relativeFilePath, sourceDir))
                .split("\n")
                .filter(line => !line.startsWith("export ")) // Remove 'export' statements.
                .join("\n").trim();
            
            await FileUtil.write(relativeFilePath.replace(".js", ".ejs"), "<!-- NOTE: This EJS file is auto-generated by 'EmbeddedScriptBuilder.ts' -->\n<script>\n" + sourceCode + "\n</script>", targetDir);
        }
    }
}