import FileUtil from "../../util/fileUtil";
import dotenv from "dotenv";
dotenv.config();

export default class EmbeddedScriptBuilder
{
    async build(sourceDir?: string, targetDir?: string): Promise<void>
    {
        if (sourceDir == undefined)
            sourceDir = `${process.env.SRC_ROOT_DIR}/shared`;
        if (targetDir == undefined)
            targetDir = `${process.env.VIEWS_ROOT_DIR}/partial/embeddedScript`;

        let relativeFilePaths = await FileUtil.getAllRelativePathsInDirRecursively(sourceDir);
        relativeFilePaths = relativeFilePaths.filter(x => x.endsWith(".js"));

        for (const relativeFilePath of relativeFilePaths)
        {
            const sourceCode = (await FileUtil.read(relativeFilePath, sourceDir))
                .split("\n")
                .filter(line => !line.startsWith("export ")) // Remove 'export' statements.
                .join("\n").trim();
            const fileIdentifier = relativeFilePath.replaceAll("/", "_");

            await FileUtil.write(relativeFilePath.replace(".js", ".ejs"), `
<% if (${fileIdentifier} != undefined) { %>
<!-- NOTE: This EJS partial is auto-generated by 'embeddedScriptBuilder.ts' -->
const ${fileIdentifier};
<script>
${sourceCode}
</script>
<% } %>
`.trim(), targetDir);
        }
    }
}