import sharp from "sharp";
import FileUtil from "../util/fileUtil";
import ImageFileUtil from "../util/imageFileUtil";
import { STATIC_PAGE_ROOT_DIR, SRC_ROOT_DIR } from "../../system/serverConstants";
import ImageMapSeed from "../../../shared/image/types/imageMapSeed";
import ImageMapSubfolderInfo from "../../../shared/image/types/imageMapSubfolderInfo";

const JPEG_QUALITY = 80;
const ASSETS_ROOT_PATH = `${STATIC_PAGE_ROOT_DIR}/app/assets`;
const MAPS_ROOT_PATH = `${SRC_ROOT_DIR}/shared/image/maps`;

export default class ImageMapBuilder
{
    private readonly rootDirName: string;
    private readonly imageRootPath: string;
    private readonly mapName: string;
    private readonly gridCellSize: number;
    private readonly maxCols: number;

    constructor(seed: ImageMapSeed)
    {
        this.rootDirName = seed.rootDirName;
        this.imageRootPath = `${ASSETS_ROOT_PATH}/${seed.rootDirName}`;
        this.mapName = seed.mapName;
        this.gridCellSize = seed.gridCellSize;
        this.maxCols = seed.maxCols;
    }

    async build(): Promise<void>
    {
        const manifestJSON = await FileUtil.read("manifest.json", this.imageRootPath);
        const manifest = JSON.parse(manifestJSON) as {images: {path: string, author: string, title: string}[]};
        
        // Collect all images
        const subfolderInfoByName: {[subfolderName: string]: ImageMapSubfolderInfo} = {};
        for (const image of manifest.images)
        {
            const subfolderName = image.path.includes("/") ? image.path.split("/")[0] : "";
            if (subfolderInfoByName[subfolderName] == undefined)
                subfolderInfoByName[subfolderName] = {name: subfolderName, images: [], gridCells: [], numGridCols: 0, numGridRows: 0};
            const info = subfolderInfoByName[subfolderName];
            info.images.push(image);
        }
        
        // Build the grid
        for (const info of Object.values(subfolderInfoByName))
            await this.buildGrid(info);
        await this.writeMapFile(subfolderInfoByName);
    }

    private async buildGrid(subfolderInfo: ImageMapSubfolderInfo): Promise<void>
    {
        const numImages = subfolderInfo.images.length;
        const numCols = numImages === 0 ? 0 : Math.min(this.maxCols, numImages);
        const numRows = numImages === 0 ? 0 : Math.ceil(numImages / numCols);
        const gridWidth = numCols === 0 ? 0 : numCols * this.gridCellSize;
        const gridHeight = numRows === 0 ? 0 : numRows * this.gridCellSize;

        const gridCells: {coords: string, path: string}[] = [];
        const composites: sharp.OverlayOptions[] = [];
        let col = 0, row = 0, maxCol = 0, maxRow = 0;

        for (const {path, author, title} of subfolderInfo.images)
        {
            const image = ImageFileUtil.readImage(`${path}.jpg`, this.imageRootPath);
            if (!image)
                throw new Error(`Image map generation failed :: Failed to read image (${this.imageRootPath}/${path}.jpg)`);
            const imageBuffer = await (image
                .resize(this.gridCellSize, this.gridCellSize, { fit: "cover" })
                .toBuffer());
            
            composites.push({input: imageBuffer, left: col * this.gridCellSize, top: row * this.gridCellSize});
            gridCells.push({coords: `${subfolderInfo.name},${col},${row}`, path});
            if (col > maxCol)
                maxCol = col;
            if (row > maxRow)
                maxRow = row;

            col = (col + 1) % numCols;
            if (col == 0)
                row++;
        }

        subfolderInfo.gridCells = gridCells;
        subfolderInfo.numGridCols = maxCol + 1;
        subfolderInfo.numGridRows = maxRow + 1;

        const gridImage = sharp({create: {width: gridWidth, height: gridHeight, channels: 3, background: {r: 0, g: 0, b: 0}}})
            .composite(composites)
            .jpeg({ quality: JPEG_QUALITY });
        await ImageFileUtil.writeImage(`${subfolderInfo.name.length == 0 ? "" : `${subfolderInfo.name}/`}grid.jpg`, gridImage, this.imageRootPath);
    }

    private async writeMapFile(subfolderInfoByName: {[subfolderName: string]: ImageMapSubfolderInfo}): Promise<void>
    {
        const subfolderInfos = Object.values(subfolderInfoByName);

        const pathByCoordsEntries =
            subfolderInfos.map(info =>
                info.gridCells.map(cell =>
                    `"${cell.coords}":"${cell.path}"`)).flat().join(",");
        const coordsByPathEntries =
            subfolderInfos.map(info =>
                info.gridCells.map(cell =>
                    `"${cell.path}":"${cell.coords}"`)).flat().join(",");
        const subfolderGridSizesEntries =
            subfolderInfos.map(info =>
                `"${info.name}":{numCols:${info.numGridCols},numRows:${info.numGridRows}}`).join(",");

        const text = `// THIS FILE IS AUTO-GENERATED BY ImageMapBuilder. DO NOT EDIT MANUALLY.
import ImageMapUtil from "../util/imageMapUtil";
import ImageMap from "../types/imageMap";

const pathByCoords: {[coords: string]: string} = {${pathByCoordsEntries}}
const coordsByPath: {[path: string]: string} = {${coordsByPathEntries}}
const subfolderGridSizes: {[subfolder: string]: {numCols: number, numRows: number}} = {${subfolderGridSizesEntries}}

ImageMapUtil.setImageMap("${this.mapName}", new ImageMap("${this.rootDirName}", ${this.gridCellSize}, subfolderGridSizes, pathByCoords, coordsByPath));
`;
        const mapNameCamelCased = this.mapName[0].toLowerCase() + this.mapName.substring(1);
        await FileUtil.write(`${mapNameCamelCased}.ts`, text, MAPS_ROOT_PATH);
    }
}