import FileUtil from "../util/fileUtil";
import { SRC_ROOT_DIR } from "../../system/serverConstants";
import { InstancedMeshCompositionCodecMap } from "../../../shared/graphics/mesh/composition/maps/instancedMeshCompositionCodecMap";
import { InstancedMeshCompositionCodecTypeEnumMap } from "../../../shared/graphics/mesh/composition/types/instancedMeshCompositionCodecType";
import InstancedMeshCompositionPart from "../../../shared/graphics/mesh/composition/types/instancedMeshCompositionPart";
import CompositionMetadataUtil from "../../../shared/graphics/mesh/composition/util/compositionMetadataUtil";
import InstancedMeshIdMap from "../../../shared/graphics/mesh/maps/instancedMeshIdMap";
import Vec3 from "../../../shared/math/types/vec3";
import StringUtil from "../../../shared/math/util/stringUtil";
import ObjectScaleUtil from "../../../shared/object/util/objectScaleUtil";
import ObjectCategoryConfigMap from "../../../shared/object/maps/objectCategoryConfigMap";
import ObjectTypeConfigMap from "../../../shared/object/maps/objectTypeConfigMap";
import ObjectTypeConfig from "../../../shared/object/types/objectTypeConfig/objectTypeConfig";
import PreEncodedCompositions from "../types/preEncodedCompositions";

const MAPS_ROOT_PATH = `${SRC_ROOT_DIR}/shared/graphics/mesh/composition/maps`;
const MAP_FILE_NAME = "instancedMeshCapacityMap.ts";

// Sizes every composed mesh for its worst case (see @docs/graphics/instanced_mesh_composition.md): a room
// holding the most objects of every category, each built as whichever type and variant uses that mesh the
// most. Objects vary independently, so taking each mesh's maximum separately is exact, not an overestimate.
export default class InstancedMeshCapacityBuilder
{
    // Takes this build's tables, since the running (compiled) app still holds the previous ones.
    static computeCapacities(compositions: PreEncodedCompositions): {[instancedMeshId: string]: number}
    {
        // A cap is shared by its category's types, so the worst case is the greediest of them, not their sum.
        const maxCountsPerCategory: {[category: string]: {[instancedMeshId: string]: number}} = {};
        for (const config of ObjectTypeConfigMap.getAllConfigs())
        {
            if (!config.components.spawnedByAny?.instancedMeshComposer)
                continue;

            const maxCountsPerObject: {[instancedMeshId: string]: number} = {};
            for (const variant of InstancedMeshCapacityBuilder.getVariants(config, compositions))
            {
                // At the type's largest, since the mesh has to hold whatever the biggest one needs.
                const counts = InstancedMeshCapacityBuilder.countPartsByMesh(variant,
                    ObjectScaleUtil.getMaxObjectSize(ObjectTypeConfigMap.getIndexByType(config.objectType)));
                for (const instancedMeshId in counts)
                    maxCountsPerObject[instancedMeshId] = Math.max(maxCountsPerObject[instancedMeshId] ?? 0, counts[instancedMeshId]);
            }
            if (maxCountsPerCategory[config.category] == undefined)
                maxCountsPerCategory[config.category] = {};
            const maxCounts = maxCountsPerCategory[config.category];
            for (const instancedMeshId in maxCountsPerObject)
                maxCounts[instancedMeshId] = Math.max(maxCounts[instancedMeshId] ?? 0, maxCountsPerObject[instancedMeshId]);
        }

        const capacities: {[instancedMeshId: string]: number} = {};
        for (const category in maxCountsPerCategory)
        {
            const maxCountPerRoom = ObjectCategoryConfigMap.getConfig(category).maxCountPerRoom;
            if (maxCountPerRoom == undefined)
                throw new Error(`Instanced mesh capacity computation failed :: category "${category}" composes meshes but has no maxCountPerRoom`);
            const maxCounts = maxCountsPerCategory[category];
            for (const instancedMeshId in maxCounts)
            {
                capacities[instancedMeshId] = (capacities[instancedMeshId] ?? 0)
                    + maxCountPerRoom * maxCounts[instancedMeshId];
            }
        }
        return capacities;
    }

    private readonly compositions: PreEncodedCompositions;

    constructor(compositions: PreEncodedCompositions)
    {
        this.compositions = compositions;
    }

    async build(): Promise<void>
    {
        const capacities = InstancedMeshCapacityBuilder.computeCapacities(this.compositions);
        const sortedCapacities: {[instancedMeshId: string]: number} = {};
        for (const instancedMeshId of Object.keys(capacities).sort())
            sortedCapacities[instancedMeshId] = capacities[instancedMeshId];

        const text = `// THIS FILE IS AUTO-GENERATED BY InstancedMeshCapacityBuilder. DO NOT EDIT MANUALLY.
// Instances each composed mesh is created with.
const InstancedMeshCapacityMap: {[instancedMeshId: string]: number} = ${JSON.stringify(sortedCapacities, null, 4)};

export default InstancedMeshCapacityMap;
`;
        await FileUtil.write(MAP_FILE_NAME, text, MAPS_ROOT_PATH);
    }

    // Full encoded strings (prefix included), each decoded by the codec its prefix names.
    private static getVariants(config: ObjectTypeConfig, compositions: PreEncodedCompositions): string[]
    {
        const composer = config.components.spawnedByAny!.instancedMeshComposer!;
        if (composer.codecType == InstancedMeshCompositionCodecTypeEnumMap.Indexed)
        {
            const indices = compositions.indicesByObjectType[config.objectType] ?? [];
            if (indices.length == 0)
                throw new Error(`Instanced mesh capacity computation failed :: objectType "${config.objectType}" uses the indexed codec but has no pre-encoded compositions`);
            return indices.map(index => compositions.encodedStrings[index]);
        }

        const prefix = CompositionMetadataUtil.getCodecPrefix(composer.codecType, composer.codecVersion);
        return InstancedMeshCompositionCodecMap[composer.codecType].getStructuralVariants()
            .map(body => prefix + body);
    }

    private static countPartsByMesh(encodedComposition: string,
        objectSize: Vec3): {[instancedMeshId: string]: number}
    {
        const codecType = StringUtil.convertVisibleASCIIToRawNumber(encodedComposition, 0);
        const parts: InstancedMeshCompositionPart[] = [];
        InstancedMeshCompositionCodecMap[codecType].decode(encodedComposition, objectSize, {}, parts);

        const counts: {[instancedMeshId: string]: number} = {};
        for (const part of parts)
        {
            const instancedMeshId = InstancedMeshIdMap.getInstancedMeshId(part.geometryId, part.materialId);
            counts[instancedMeshId] = (counts[instancedMeshId] ?? 0) + 1;
        }
        return counts;
    }
}
