import FileUtil from "../util/fileUtil";
import { SRC_ROOT_DIR } from "../../system/serverConstants";
import { InstancedMeshCompositionCodecMap } from "../../../shared/graphics/mesh/composition/maps/instancedMeshCompositionCodecMap";
import { InstancedMeshCompositionCodecTypeEnumMap } from "../../../shared/graphics/mesh/composition/types/instancedMeshCompositionCodecType";
import InstancedMeshCompositionPart from "../../../shared/graphics/mesh/composition/types/instancedMeshCompositionPart";
import CompositionMetadataUtil from "../../../shared/graphics/mesh/composition/util/compositionMetadataUtil";
import StringUtil from "../../../shared/math/util/stringUtil";
import ObjectTypeConfigMap from "../../../shared/object/maps/objectTypeConfigMap";
import ObjectTypeConfig from "../../../shared/object/types/objectTypeConfig/objectTypeConfig";
import PreEncodedCompositions from "../types/preEncodedCompositions";

const MAPS_ROOT_PATH = `${SRC_ROOT_DIR}/shared/graphics/mesh/composition/maps`;
const MAP_FILE_NAME = "instancedMeshCapacityMap.ts";

// Sizes every composed mesh for its worst case (see @docs/graphics/instanced_mesh_composition.md): a room
// holding the most objects of every type, each built as whichever variant uses that mesh the most. Objects
// of a type vary independently, so taking each mesh's maximum separately is exact, not an overestimate.
export default class InstancedMeshCapacityBuilder
{
    // Takes this build's tables, since the running (compiled) app still holds the previous ones.
    static computeCapacities(compositions: PreEncodedCompositions): {[instancedMeshId: string]: number}
    {
        const capacities: {[instancedMeshId: string]: number} = {};
        for (const config of ObjectTypeConfigMap.getAllConfigs())
        {
            if (!config.components.spawnedByAny?.instancedMeshComposer)
                continue;
            if (config.maxCountPerRoom == undefined)
                throw new Error(`Instanced mesh capacity computation failed :: objectType "${config.objectType}" composes meshes but has no maxCountPerRoom`);

            const maxCountsPerObject: {[instancedMeshId: string]: number} = {};
            for (const variant of InstancedMeshCapacityBuilder.getVariants(config, compositions))
            {
                const counts = InstancedMeshCapacityBuilder.countPartsByMesh(variant);
                for (const instancedMeshId in counts)
                    maxCountsPerObject[instancedMeshId] = Math.max(maxCountsPerObject[instancedMeshId] ?? 0, counts[instancedMeshId]);
            }
            for (const instancedMeshId in maxCountsPerObject)
            {
                capacities[instancedMeshId] = (capacities[instancedMeshId] ?? 0)
                    + config.maxCountPerRoom * maxCountsPerObject[instancedMeshId];
            }
        }
        return capacities;
    }

    private readonly compositions: PreEncodedCompositions;

    constructor(compositions: PreEncodedCompositions)
    {
        this.compositions = compositions;
    }

    async build(): Promise<void>
    {
        const capacities = InstancedMeshCapacityBuilder.computeCapacities(this.compositions);
        const sortedCapacities: {[instancedMeshId: string]: number} = {};
        for (const instancedMeshId of Object.keys(capacities).sort())
            sortedCapacities[instancedMeshId] = capacities[instancedMeshId];

        const text = `// THIS FILE IS AUTO-GENERATED BY InstancedMeshCapacityBuilder. DO NOT EDIT MANUALLY.
// Instances each composed mesh is created with.
const InstancedMeshCapacityMap: {[instancedMeshId: string]: number} = ${JSON.stringify(sortedCapacities, null, 4)};

export default InstancedMeshCapacityMap;
`;
        await FileUtil.write(MAP_FILE_NAME, text, MAPS_ROOT_PATH);
    }

    // Full encoded strings (prefix included), each decoded by the codec its prefix names.
    private static getVariants(config: ObjectTypeConfig, compositions: PreEncodedCompositions): string[]
    {
        const composer = config.components.spawnedByAny!.instancedMeshComposer!;
        if (composer.codecType == InstancedMeshCompositionCodecTypeEnumMap.Indexed)
        {
            const indices = compositions.indicesByObjectType[config.objectType] ?? [];
            if (indices.length == 0)
                throw new Error(`Instanced mesh capacity computation failed :: objectType "${config.objectType}" uses the indexed codec but has no pre-encoded compositions`);
            return indices.map(index => compositions.encodedStrings[index]);
        }

        const prefix = CompositionMetadataUtil.getCodecPrefix(composer.codecType, composer.codecVersion);
        return InstancedMeshCompositionCodecMap[composer.codecType].getStructuralVariants()
            .map(body => prefix + body);
    }

    private static countPartsByMesh(encodedComposition: string): {[instancedMeshId: string]: number}
    {
        const codecType = StringUtil.convertVisibleASCIIToRawNumber(encodedComposition, 0);
        const parts: InstancedMeshCompositionPart[] = [];
        InstancedMeshCompositionCodecMap[codecType].decode(encodedComposition, {}, parts);

        const counts: {[instancedMeshId: string]: number} = {};
        for (const part of parts)
            counts[part.instancedMeshId] = (counts[part.instancedMeshId] ?? 0) + 1;
        return counts;
    }
}
