import FileUtil from "../util/fileUtil";
import { STATIC_PAGE_ROOT_DIR, SRC_ROOT_DIR } from "../../system/serverConstants";
import PreEncodingSourceEntry from "../../../shared/graphics/mesh/composition/types/preEncodingSourceEntry";
import PreEncodingSourceUtil from "../../../shared/graphics/mesh/composition/util/preEncodingSourceUtil";
import PreEncodedCompositions from "../types/preEncodedCompositions";

const SOURCE_ROOT_PATH = `${STATIC_PAGE_ROOT_DIR}/app/assets/instanced_mesh_composition`;
const SOURCE_FILE_NAME = "pre_encoding_source.json";
const MAPS_ROOT_PATH = `${SRC_ROOT_DIR}/shared/graphics/mesh/composition/maps`;
const STRING_MAP_FILE_NAME = "preEncodedCompositionStringMap.ts";
const INDEX_MAP_FILE_NAME = "preEncodedCompositionIndexMap.ts";

// Encodes authored compositions into the generated indexed tables at build time (see
// @docs/graphics/instanced_mesh_composition.md). Any source error fails the build, since bad entries
// fail silently at runtime and can't be fixed once objects reference their index.
export default class PreEncodedCompositionBuilder
{
    // Returns what it wrote, since the running (compiled) app still holds the previous tables.
    async build(): Promise<PreEncodedCompositions>
    {
        const sourceJSON = await FileUtil.read(SOURCE_FILE_NAME, SOURCE_ROOT_PATH);
        const source = JSON.parse(sourceJSON) as {compositions: PreEncodingSourceEntry[]};

        const encodedStrings: string[] = [];
        const indicesByObjectType: {[objectType: string]: number[]} = {};
        source.compositions.forEach((entry, compositionIndex) => {
            encodedStrings.push(PreEncodingSourceUtil.encodeEntry(entry, compositionIndex));
            (indicesByObjectType[entry.objectType] ??= []).push(compositionIndex);
        });

        await this.writeStringMapFile(encodedStrings);
        await this.writeIndexMapFile(indicesByObjectType);
        return {encodedStrings, indicesByObjectType};
    }

    private async writeStringMapFile(encodedStrings: string[]): Promise<void>
    {
        // JSON.stringify, since the alphabet includes quotes and backslashes.
        const entries = encodedStrings.map(str => JSON.stringify(str)).join(",");

        const text = `// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
const PreEncodedCompositionStringMap: string[] = [${entries}];

export default PreEncodedCompositionStringMap;
`;
        await FileUtil.write(STRING_MAP_FILE_NAME, text, MAPS_ROOT_PATH);
    }

    private async writeIndexMapFile(indicesByObjectType: {[objectType: string]: number[]}): Promise<void>
    {
        const text = `// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
// Positions in PreEncodedCompositionStringMap that belong to each object type, in source order.
const PreEncodedCompositionIndexMap: {[objectType: string]: number[]} = ${JSON.stringify(indicesByObjectType)};

export default PreEncodedCompositionIndexMap;
`;
        await FileUtil.write(INDEX_MAP_FILE_NAME, text, MAPS_ROOT_PATH);
    }
}
