import fs from "fs/promises";
import FileUtil from "../util/fileUtil";
import { STATIC_PAGE_ROOT_DIR, SRC_ROOT_DIR } from "../../system/serverConstants";
import ServerRoomFileUtil from "../../room/util/serverRoomFileUtil";
import RoomFile from "../../../shared/room/types/roomFile";
import RoomMapSeed from "../../../shared/room/types/roomMapSeed";
import ErrorUtil from "../../../shared/system/util/errorUtil";

const ASSETS_ROOT_PATH = `${STATIC_PAGE_ROOT_DIR}/app/assets`;
const MAPS_ROOT_PATH = `${SRC_ROOT_DIR}/shared/room/maps`;

// Any room serves to read a file into, as one names none (see RoomFile).
const PLACEHOLDER_ROOM_ID = "room";

// Lists the room files under a map's root directory in a TypeScript module that registers the map in
// RoomMapUtil (see @docs/networking/single_player_mode.md). A file this build can't read as a room fails the
// build here, rather than the game when somebody enters it.
export default class RoomMapBuilder
{
    private readonly rootDirName: string;
    private readonly roomRootPath: string;
    private readonly mapName: string;

    constructor(seed: RoomMapSeed)
    {
        this.rootDirName = seed.rootDirName;
        this.roomRootPath = `${ASSETS_ROOT_PATH}/${seed.rootDirName}`;
        this.mapName = seed.mapName;
    }

    async build(): Promise<void>
    {
        const roomPaths = (await FileUtil.getAllRelativePathsInDirRecursively(this.roomRootPath))
            .filter(filePath => filePath.endsWith(RoomFile.FILE_EXTENSION))
            .map(filePath => filePath.slice(0, -RoomFile.FILE_EXTENSION.length))
            .sort();
        if (roomPaths.length == 0)
            throw new Error(`Room map generation failed :: No room files found (mapName = ${this.mapName})`);

        for (const roomPath of roomPaths)
        {
            const bytes = await fs.readFile(
                FileUtil.getAbsoluteFilePath(`${roomPath}${RoomFile.FILE_EXTENSION}`, this.roomRootPath));
            try
            {
                ServerRoomFileUtil.decode(bytes, PLACEHOLDER_ROOM_ID);
            }
            catch (err)
            {
                throw new Error(`Room map generation failed :: "${roomPath}" can't be read as a room (mapName = ${this.mapName}, error = ${ErrorUtil.getErrorMessage(err)})`);
            }
        }

        // NOTE: import paths below are relative to the generated file (MAPS_ROOT_PATH).
        const text = `// THIS FILE IS AUTO-GENERATED BY RoomMapBuilder. DO NOT EDIT MANUALLY.
import RoomMapUtil from "../util/roomMapUtil";
import RoomMap from "../types/roomMap";

const roomPaths: string[] = ${JSON.stringify(roomPaths)}

RoomMapUtil.setRoomMap("${this.mapName}", new RoomMap("${this.rootDirName}", roomPaths));
`;
        const mapKey = this.mapName.charAt(0).toLowerCase() + this.mapName.slice(1);
        await FileUtil.write(`${mapKey}.ts`, text, MAPS_ROOT_PATH);
    }
}
