import "../types/objectTypeClientConfig/voxelObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/playerObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/canvasObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/doorObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/lampObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/labelObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/propObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/npcObjectTypeClientConfig.ts";
import "../types/objectTypeClientConfig/volumeObjectTypeClientConfig.ts";
