// THIS FILE IS AUTO-GENERATED BY ImageMapBuilder. DO NOT EDIT MANUALLY.
import ImageMapUtil from "../util/imageMapUtil";
import ImageMap from "../types/imageMap";

const pathByCoords: {[coords: string]: string} = {"1,0,0":"1/1","1,1,0":"1/2","1,2,0":"1/3","1,3,0":"1/4","1,0,1":"1/5","1,1,1":"1/6","1,2,1":"1/7","1,3,1":"1/8","1,0,2":"1/9","1,1,2":"1/10","1,2,2":"1/11","1,3,2":"1/12","1,0,3":"1/13","1,1,3":"1/14","1,2,3":"1/15","1,3,3":"1/16","1,0,4":"1/17","1,1,4":"1/18","1,2,4":"1/19","1,3,4":"1/20","1,0,5":"1/21","1,1,5":"1/22","1,2,5":"1/23","1,3,5":"1/24","1,0,6":"1/25"}
const coordsByPath: {[path: string]: string} = {"1/1":"1,0,0","1/2":"1,1,0","1/3":"1,2,0","1/4":"1,3,0","1/5":"1,0,1","1/6":"1,1,1","1/7":"1,2,1","1/8":"1,3,1","1/9":"1,0,2","1/10":"1,1,2","1/11":"1,2,2","1/12":"1,3,2","1/13":"1,0,3","1/14":"1,1,3","1/15":"1,2,3","1/16":"1,3,3","1/17":"1,0,4","1/18":"1,1,4","1/19":"1,2,4","1/20":"1,3,4","1/21":"1,0,5","1/22":"1,1,5","1/23":"1,2,5","1/24":"1,3,5","1/25":"1,0,6"}
const subfolderGridSizes: {[subfolder: string]: {numCols: number, numRows: number}} = {"1":{numCols:4,numRows:7}}

ImageMapUtil.setImageMap("CanvasImageMap", new ImageMap("canvas_images", 128, subfolderGridSizes, pathByCoords, coordsByPath));
