// THIS FILE IS AUTO-GENERATED BY ImageMapBuilder. DO NOT EDIT MANUALLY.
import ImageMapUtil from "../util/imageMapUtil";
import ImageMap from "../types/imageMap";

const pathByCoords: {[coords: string]: string} = {",0,0":"default",",1,0":"country",",0,1":"garden",",1,1":"aqua",",0,2":"inferno",",1,2":"prison"}
const coordsByPath: {[path: string]: string} = {"default":",0,0","country":",1,0","garden":",0,1","aqua":",1,1","inferno":",0,2","prison":",1,2"}
const subfolderGridSizes: {[subfolder: string]: {numCols: number, numRows: number}} = {"":{numCols:2,numRows:3}}

ImageMapUtil.setImageMap("TexturePackImageMap", new ImageMap("texture_packs", 256, subfolderGridSizes, pathByCoords, coordsByPath));
