export const COLLISION_LAYER_00_TO_05 = 0;
export const COLLISION_LAYER_05_TO_10 = 1;
export const COLLISION_LAYER_10_TO_15 = 2;
export const COLLISION_LAYER_15_TO_20 = 3;
export const COLLISION_LAYER_20_TO_25 = 4;
export const COLLISION_LAYER_25_TO_30 = 5;
export const COLLISION_LAYER_30_TO_35 = 6;
export const COLLISION_LAYER_35_TO_40 = 7;
export const COLLISION_LAYER_FLOOR_AND_CEILING = 8;

export const COLLISION_LAYER_MIN = COLLISION_LAYER_00_TO_05;
export const COLLISION_LAYER_MAX = COLLISION_LAYER_35_TO_40;