// THIS FILE IS AUTO-GENERATED BY RoomMapBuilder. DO NOT EDIT MANUALLY.
import RoomMapUtil from "../util/roomMapUtil";
import RoomMap from "../types/roomMap";

const roomPaths: string[] = ["empty","sandbox","tutorial"]

RoomMapUtil.setRoomMap("SinglePlayerRoomMap", new RoomMap("rooms", roomPaths));
