// THIS FILE IS AUTO-GENERATED BY InstancedMeshCapacityBuilder. DO NOT EDIT MANUALLY.
// Instances each composed mesh is created with.
const InstancedMeshCapacityMap: {[instancedMeshId: string]: number} = {
    "Box+InstancedTin": 1152,
    "Cylinder+InstancedTin": 768,
    "Square+InstancedEmissive": 256,
    "Square+InstancedWood": 192
};

export default InstancedMeshCapacityMap;
