// THIS FILE IS AUTO-GENERATED BY InstancedMeshCapacityBuilder. DO NOT EDIT MANUALLY.
// Instances each composed mesh is created with.
const InstancedMeshCapacityMap: {[instancedMeshId: string]: number} = {
    "Box+InstancedTin": 1440,
    "Cylinder+InstancedTin": 960,
    "Square+InstancedEmissive": 304,
    "Square+InstancedWood": 384
};

export default InstancedMeshCapacityMap;
