// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
const PreEncodedCompositionStringMap: string[] = ["!\"%&PPPTTX!","!\"%&PPPXTX!","!\"%&PPPTXX!","!\"%&PPPXXX!"];

export default PreEncodedCompositionStringMap;
