// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
const PreEncodedCompositionStringMap: string[] = ["!!!%PP~PPPF4F~~~"];

export default PreEncodedCompositionStringMap;
