// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
const PreEncodedCompositionStringMap: string[] = ["!\"%&PPPTTX!","!\"%&PPPXTX!","!\"%&PPPTXX!","!\"%&PPPXXX!","(!!!!!","(!#,'$","(!(7%$","(!31#$","(!%#$$","(!YL##","(!a-$$","(!iF$#","(!ZN\"$","(!H!##","(!3>&#","(![O$#","(!Ib!$","(!?:%#","(!YM#$","(!P\\'$","(!kF\"$","(!!!!!","(!=,\"$","(!(>#$","(!2#%$","(!ZM#$","(!R,'#","(!iE\"#","(!7G&#","(!NZ\"#","#!$\"T","#!(&>","#!HH1","#!O$'","#!2.=","#!ESG","#!UHb","#!MLY","#!N4(","#!\"\"/","#!iPS","#!aaB","(!VH%$","(!9'!$","(!n3$#","(!LX#$","#!KLM","#!/@<","#![OP","#!F\";"];

export default PreEncodedCompositionStringMap;
