// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
// Positions in PreEncodedCompositionStringMap that belong to each object type, in source order.
const PreEncodedCompositionIndexMap: {[objectType: string]: number[]} = {"Lamp":[0,1,2,3],"Canvas":[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,62,63,64,65],"Label":[21,22,23,24,25,26,27,28,29,42,43,44,45,50,51,52,53,54,55,56,57],"Door":[30,31,32,33,34,35,36,37,38,39,40,41,46,47,48,49,58,59,60,61]};

export default PreEncodedCompositionIndexMap;
