// THIS FILE IS AUTO-GENERATED BY PreEncodedCompositionBuilder. DO NOT EDIT MANUALLY.
// Positions in PreEncodedCompositionStringMap that belong to each object type, in source order.
const PreEncodedCompositionIndexMap: {[objectType: string]: number[]} = {};

export default PreEncodedCompositionIndexMap;
