// THIS FILE IS AUTO-GENERATED BY ImageMapBuilder. DO NOT EDIT MANUALLY.
import ImageMapUtil from "../util/imageMapUtil";
import ImageMap from "../types/imageMap";
import ImageMetadata from "../types/imageMetadata";

const imageMetadataList: ImageMetadata[] = [{path:"0,0",author:"",title:"",coords:",0,0"},{path:"0,1",author:"",title:"",coords:",0,1"},{path:"0,2",author:"",title:"",coords:",0,2"},{path:"0,3",author:"",title:"",coords:",0,3"},{path:"1,0",author:"",title:"",coords:",1,0"},{path:"1,1",author:"",title:"",coords:",1,1"},{path:"1,2",author:"",title:"",coords:",1,2"},{path:"1,3",author:"",title:"",coords:",1,3"},{path:"2,0",author:"",title:"",coords:",2,0"},{path:"2,1",author:"",title:"",coords:",2,1"},{path:"2,2",author:"",title:"",coords:",2,2"},{path:"2,3",author:"",title:"",coords:",2,3"},{path:"3,0",author:"",title:"",coords:",3,0"},{path:"3,1",author:"",title:"",coords:",3,1"},{path:"3,2",author:"",title:"",coords:",3,2"},{path:"3,3",author:"",title:"",coords:",3,3"}]
const subfolderGridSizes: {[subfolder: string]: {numCols: number, numRows: number}} = {"":{numCols:4,numRows:4}}

ImageMapUtil.setImageMap("CanvasFrameImageMap", new ImageMap("object_texture_packs", 256, subfolderGridSizes, imageMetadataList, "canvas_frames"));
