// THIS FILE IS AUTO-GENERATED BY ImageMapBuilder. DO NOT EDIT MANUALLY.
import ImageMapUtil from "../util/imageMapUtil";
import ImageMap from "../types/imageMap";
import ImageMetadata from "../types/imageMetadata";

const imageMetadataList: ImageMetadata[] = [{path:"default",author:"",title:"default",coords:",0,0"},{path:"country",author:"",title:"country",coords:",1,0"},{path:"garden",author:"",title:"garden",coords:",0,1"},{path:"aqua",author:"",title:"aqua",coords:",1,1"},{path:"inferno",author:"",title:"inferno",coords:",0,2"},{path:"prison",author:"",title:"prison",coords:",1,2"}]
const subfolderGridSizes: {[subfolder: string]: {numCols: number, numRows: number}} = {"":{numCols:2,numRows:3}}

ImageMapUtil.setImageMap("TexturePackImageMap", new ImageMap("texture_packs", 256, subfolderGridSizes, imageMetadataList));
