const defaultRoomMap = `
GGGGGGGGGGAAAAAAAAACCCCCCCCCCCCC
GggggggggGaHaHaHaHaCcccccccccccC
GggggggggGaaaaaaaaaCcccccccccccC
GggggggggGaaaaaaaaaCCCCCccccCccC
GggggggggGaaaaaaaaaaaaabbbbbbbbB
GggggggggGaaaaahhhhhaaabbbbbBbbB
KaaaaaaaaaaaaaahjjjhaaabbbbbbbbB
KaaaaaaaaaaaaaahjjjhaaabbbbbbbbB
KaaaaaaaaaaaaaahjjjhaaaBBBBBBBBB
DDDDDDDDDaaaaaahjjjhaaaeeeeeeeeE
DdddddddddddaaahjjjhaaaeeeeeeeeE
DdddddddddddaaahhhhhaaaEeeeeeeeE
DdddddddddddaaaaaaaaaaaEeeeeeeeE
DdddddddddddDaaaaaaaaaaEeeeeeeeE
DdddddddddddDiiiiiiiiiiEJeeeeeeE
DDDDDDDDDDDDDiiiiiiiiiiEEEEEEEEE
LLLLLLLLLLmmmmmmmmmNNNNNNNNNNNNN
LllllllllLmmmmmmmmmnnnnnnnnnnnnN
LllllllllLmmmooommmnnnnnnnnnnnnN
LllllllllLmmmooommmnnnnPnnnnnnON
LlllllllllmmmooommmnnnnPnnnnnnnN
LlllllllllmmmooommmnnnnPnnnnnnON
LllllllllLmmmooommmnnnnPnnnnnnnN
LllllllllLmmmooommmnnnnnnnnnnnON
LLLLLLLLLLmmmmmmmmmnnnnnnnnnnnnN
RrrrrrrrssmmmmmmmmmNNqqqqqNNNNNN
RrrrrrrrsssssssssssQQqqqqqQQQQQQ
RrrrrrrRSssssssssssQqqqqqqqqqqqQ
RrrrrrrRSssssssssssQqqqqqqqqqqqQ
RrrrrrrRSssssssssssQqqqqqqqqqqqQ
RrrrrrrRSssssssssssQqqqqqqqqqqqQ
RRRRRRRRSSSSSSSSSSSQQQQQQQQQQQQQ
`.split("\n").map(x => x.trim()).filter(x => x.length > 0).join("\n");

const simpleRoomMap = `
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
GgggggDgDgDgDgDgDgDgDggggggggggG
GggggggggggggggggggggggggggggggG
GggggggggggggggggggggggggggggggG
GggggggggggggggggggggggggggggggG
BBBBBBBBBggggggggGGGGGGGGGGGGGGG
BbbbbbbbBggggggggGgggggggggggggG
BbbbbbbbBggggggggGgggggggggggggG
BEbbbbbbBggggggggGgggggggggggggG
BbbbbbbbBeeeeeeeeeeeeeeeCccccccC
BEbbbbbbBeeeeeeeeeeeeeeeCccccccC
BbbbbbbbBeeeeeeeeeeeeeeeCCCCCCCC
BEbbbbbbBeeeeiiiiiiieeeeCccccccC
BbbbbbbbBeeeeiiiiiiieeeeCccccccC
GddddddddeeeeiiiiiiieeeeCccccccC
GGdddddddeeeeiiiiiiieeeeCccccccC
GddddddddeeeeeeeeeeeeeeeCccccccC
GGdddddddeeeeeeeeeeeeeeeCccccccC
GddddddddeeeeeeeeeeeeeeegggggggG
GGGGGGGGGGGGGGgggggggggggggggggG
GggggggggggggggggggggggggggggggG
GgggggggggggggggggggggggHhhhhhhH
FffffffffffffFggggggggggHhhhhhhH
FffffffffffffFggggggggggHhhhhhhH
FffffffffffffFggggggggggHhhhhhhH
FffffffffffffFggggggggggHhhhhhhH
FffffffffffffFggggggggggHhhhhhhH
FffffffffffffFggggHHHHHHHHHHHHHH
FffffffffffffFgggggggggggggggggG
FffffffffffffFgggggggggggggggggG
FffffffffffffFgggggggggggggggggG
FFFFFFFFFFFFFFGGGGGGGGGGGGGGGGGG
`.split("\n").map(x => x.trim()).filter(x => x.length > 0).join("\n");

const RoomMaps: {[roomName: string]: string} =
{
    "room_default_2": defaultRoomMap,
    "room_default": simpleRoomMap,
}

export default RoomMaps;